// Generated by CoffeeScript 1.6.2
(function() {
  suite('Gilded Rose', function() {
    setup(function() {
      var _this = this;

      this.worker = Elm.worker(Elm.GildedRose);
      this.send = function(num) {
        this.lastOutput = null;
        return this.worker.send("input", num);
      };
      this.check = function(against, lastCallback) {
        this.against = against;
        this.lastCallback = lastCallback;
      };
      return this.worker.recv("output", function(evt) {
        _this.lastOutput = evt.value;
        _this.against.should.equal(_this.lastOutput);
        if (typeof _this.lastCallback === "function") {
          _this.lastCallback();
        }
        return _this.lastCallback = null;
      });
    });
    test('Can calculate factorial', function(done) {
      this.timeout(500);
      this.check(6, done);
      return this.send(3);
    });
    return test('This fails', function(done) {
      this.timeout(500);
      this.check(16, done);
      return this.send(3);
    });
  });

}).call(this);
