// Generated by CoffeeScript 1.6.2
(function() {
  suite('Gilded Rose', function() {
    setup(function() {
      return this.worker = Elm.worker(Elm.GildedRose);
    });
    return test('Can calculate factorial', function(done) {
      this.timeout(500);
      this.worker.recv("output", function(result) {
        result.should.equal(6);
        return done();
      });
      return this.worker.send("factorial", 3);
    });
  });

}).call(this);
